
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

#include <tracer.h>

BYTE conv[256] = {
  
/* FTrace_EVT_ticks_per_sec      0x00 */ NOT_DEFINED,
/* FTrace_EVT_cycles_per_tick    0x10 */ NOT_DEFINED,
/* FTrace_EVT_trace_start        0x20 */ NOT_DEFINED,
/* FTrace_EVT_trace_stop         0x30 */ NOT_DEFINED,
/* FTrace_EVT_blackout_start     0x40 */ NOT_DEFINED,
/* FTrace_EVT_blackout_end       0x50 */ NOT_DEFINED,
/* FTrace_EVT_id                 0x60 */ NOT_DEFINED,
/* FTrace_EVT_numeevents         0x70 */ NOT_DEFINED,
                             /*  0x80 */ NOT_DEFINED,
                             /*  0x90 */ NOT_DEFINED,
                             /*  0xA0 */ NOT_DEFINED,
                             /*  0xB0 */ NOT_DEFINED,
                             /*  0xC0 */ NOT_DEFINED,
                             /*  0xD0 */ NOT_DEFINED,
                             /*  0xE0 */ NOT_DEFINED,
                             /*  0xF0 */ NOT_DEFINED,
/* FTrace_EVT_ipoint             0x01 */ NOT_DEFINED,
                             /*  0x11 */ NOT_DEFINED,
                             /*  0x21 */ NOT_DEFINED,
                             /*  0x31 */ NOT_DEFINED,
                             /*  0x41 */ NOT_DEFINED,
                             /*  0x51 */ NOT_DEFINED,
                             /*  0x61 */ NOT_DEFINED,
                             /*  0x71 */ NOT_DEFINED,
                             /*  0x81 */ NOT_DEFINED,
                             /*  0x91 */ NOT_DEFINED,
                             /*  0xA1 */ NOT_DEFINED,
                             /*  0xB1 */ NOT_DEFINED,
                             /*  0xC1 */ NOT_DEFINED,
                             /*  0xD1 */ NOT_DEFINED,
                             /*  0xE1 */ NOT_DEFINED,
                             /*  0xF1 */ NOT_DEFINED,
/* FTrace_EVT_task_create        0x02 */ NOT_DEFINED,
/* FTrace_EVT_task_activate      0x12 */ NOT_DEFINED,
/* FTrace_EVT_task_dispatch      0x22 */ NOT_DEFINED,
/* FTrace_EVT_task_epilogue      0x32 */ NOT_DEFINED,
/* FTrace_EVT_task_end           0x42 */ NOT_DEFINED,
/* FTrace_EVT_task_begin_cycle   0x52 */ NOT_DEFINED,
/* FTrace_EVT_task_end_cycle     0x62 */ NOT_DEFINED,
/* FTrace_EVT_task_sleep         0x72 */ NOT_DEFINED,
/* FTrace_EVT_task_schedule      0x82 */ NOT_DEFINED,
                             /*  0x92 */ NOT_DEFINED,
                             /*  0xA2 */ NOT_DEFINED,
                             /*  0xB2 */ NOT_DEFINED,
                             /*  0xC2 */ NOT_DEFINED,
                             /*  0xD2 */ NOT_DEFINED,
                             /*  0xE2 */ NOT_DEFINED,
                             /*  0xF2 */ NOT_DEFINED,
/* FTrace_EVT_interrupt_start    0x03 */ NOT_DEFINED,
/* FTrace_EVT_interrupt_end      0x13 */ NOT_DEFINED,
/* FTrace_EVT_interrupt_hit      0x23 */ NOT_DEFINED,
/* FTrace_EVT_interrupt_count    0x33 */ NOT_DEFINED, 
                             /*  0x43 */ NOT_DEFINED,
                             /*  0x53 */ NOT_DEFINED,
                             /*  0x63 */ NOT_DEFINED,
                             /*  0x73 */ NOT_DEFINED,
                             /*  0x83 */ NOT_DEFINED,
                             /*  0x93 */ NOT_DEFINED,
                             /*  0xA3 */ NOT_DEFINED,
                             /*  0xB3 */ NOT_DEFINED,
                             /*  0xC3 */ NOT_DEFINED,
                             /*  0xD3 */ NOT_DEFINED,
                             /*  0xE3 */ NOT_DEFINED,
                             /*  0xF3 */ NOT_DEFINED,
/* FTrace_EVT_to_real_mode       0x04 */ NOT_DEFINED,
/* FTrace_EVT_to_protected_mode  0x14 */ NOT_DEFINED,
/* FTrace_EVT_CLI                0x24 */ NOT_DEFINED,
/* FTrace_EVT_STI                0x34 */ NOT_DEFINED,
                             /*  0x44 */ NOT_DEFINED,
                             /*  0x54 */ NOT_DEFINED,
                             /*  0x64 */ NOT_DEFINED,
                             /*  0x74 */ NOT_DEFINED,
                             /*  0x84 */ NOT_DEFINED,
                             /*  0x94 */ NOT_DEFINED,
                             /*  0xA4 */ NOT_DEFINED,
                             /*  0xB4 */ NOT_DEFINED,
                             /*  0xC4 */ NOT_DEFINED,
                             /*  0xD4 */ NOT_DEFINED,
                             /*  0xE4 */ NOT_DEFINED,
                             /*  0xF4 */ NOT_DEFINED,
/* FTrace_EVT_set_priority       0x05 */ NOT_DEFINED,
/* FTrace_EVT_context_switch     0x15 */ NOT_DEFINED,
                             /*  0x25 */ NOT_DEFINED,
                             /*  0x35 */ NOT_DEFINED,
                             /*  0x45 */ NOT_DEFINED,
                             /*  0x55 */ NOT_DEFINED,
                             /*  0x65 */ NOT_DEFINED,
                             /*  0x75 */ NOT_DEFINED,
                             /*  0x85 */ NOT_DEFINED,
                             /*  0x95 */ NOT_DEFINED,
                             /*  0xA5 */ NOT_DEFINED,
                             /*  0xB5 */ NOT_DEFINED,
                             /*  0xC5 */ NOT_DEFINED,
                             /*  0xD5 */ NOT_DEFINED,
                             /*  0xE5 */ NOT_DEFINED,
                             /*  0xF5 */ NOT_DEFINED,
/* FTrace_EVT_set_mutex_create   0x06 */ NOT_DEFINED,
/* FTrace_EVT_set_mutex_lock     0x16 */ NOT_DEFINED,
/* FTrace_EVT_set_mutex_inherit  0x26 */ NOT_DEFINED,
/* FTrace_EVT_set_mutex_unlock   0x36 */ NOT_DEFINED,
                             /*  0x46 */ NOT_DEFINED,
                             /*  0x56 */ NOT_DEFINED,
                             /*  0x66 */ NOT_DEFINED,
                             /*  0x76 */ NOT_DEFINED,
                             /*  0x86 */ NOT_DEFINED,
                             /*  0x96 */ NOT_DEFINED,
                             /*  0xA6 */ NOT_DEFINED,
                             /*  0xB6 */ NOT_DEFINED,
                             /*  0xC6 */ NOT_DEFINED,
                             /*  0xD6 */ NOT_DEFINED,
                             /*  0xE6 */ NOT_DEFINED,
                             /*  0xF6 */ NOT_DEFINED,
/* FTrace_EVT_signal             0x07 */ NOT_DEFINED,
                             /*  0x17 */ NOT_DEFINED,
                             /*  0x27 */ NOT_DEFINED,
                             /*  0x37 */ NOT_DEFINED,
                             /*  0x47 */ NOT_DEFINED,
                             /*  0x57 */ NOT_DEFINED,
                             /*  0x67 */ NOT_DEFINED,
                             /*  0x77 */ NOT_DEFINED,
                             /*  0x87 */ NOT_DEFINED,
                             /*  0x97 */ NOT_DEFINED,
                             /*  0xA7 */ NOT_DEFINED,
                             /*  0xB7 */ NOT_DEFINED,
                             /*  0xC7 */ NOT_DEFINED,
                             /*  0xD7 */ NOT_DEFINED,
                             /*  0xE7 */ NOT_DEFINED,
                             /*  0xF7 */ NOT_DEFINED,
/* FTrace_EVT_server_create      0x08 */ NOT_DEFINED,
/* FTrace_EVT_server_replenish   0x18 */ NOT_DEFINED,
/* FTrace_EVT_server_exhaust     0x28 */ NOT_DEFINED,
                             /*  0x38 */ NOT_DEFINED,
                             /*  0x48 */ NOT_DEFINED,
                             /*  0x58 */ NOT_DEFINED,
                             /*  0x68 */ NOT_DEFINED,
                             /*  0x78 */ NOT_DEFINED,
                             /*  0x88 */ NOT_DEFINED,
                             /*  0x98 */ NOT_DEFINED,
                             /*  0xA8 */ NOT_DEFINED,
                             /*  0xB8 */ NOT_DEFINED,
                             /*  0xC8 */ NOT_DEFINED,
                             /*  0xD8 */ NOT_DEFINED,
                             /*  0xE8 */ NOT_DEFINED,
                             /*  0xF8 */ NOT_DEFINED,
/* FTrace_EVT_user_event_0       0x09 */ NOT_DEFINED,
/* FTrace_EVT_user_event_1       0x19 */ NOT_DEFINED,
/* FTrace_EVT_user_event_2       0x29 */ NOT_DEFINED,
/* FTrace_EVT_user_event_3       0x39 */ NOT_DEFINED,
/* FTrace_EVT_user_event_4       0x49 */ NOT_DEFINED,
/* FTrace_EVT_user_event_5       0x59 */ NOT_DEFINED,
/* FTrace_EVT_user_event_6       0x69 */ NOT_DEFINED,
/* FTrace_EVT_user_event_7       0x79 */ NOT_DEFINED,
/* FTrace_EVT_user_event_8       0x89 */ NOT_DEFINED,
/* FTrace_EVT_user_event_9       0x99 */ NOT_DEFINED,
/* FTrace_EVT_user_event_10      0xA9 */ NOT_DEFINED,
/* FTrace_EVT_user_event_11      0xB9 */ NOT_DEFINED,
/* FTrace_EVT_user_event_12      0xC9 */ NOT_DEFINED,
/* FTrace_EVT_user_event_13      0xD9 */ NOT_DEFINED,
/* FTrace_EVT_user_event_14      0xE9 */ NOT_DEFINED,
/* FTrace_EVT_user_event_15      0xF9 */ NOT_DEFINED,
                             /*  0x0A */ NOT_DEFINED,
                             /*  0x1A */ NOT_DEFINED,
                             /*  0x2A */ NOT_DEFINED,
                             /*  0x3A */ NOT_DEFINED,
                             /*  0x4A */ NOT_DEFINED,
                             /*  0x5A */ NOT_DEFINED,
                             /*  0x6A */ NOT_DEFINED,
                             /*  0x7A */ NOT_DEFINED,
                             /*  0x8A */ NOT_DEFINED,
                             /*  0x9A */ NOT_DEFINED,
                             /*  0xAA */ NOT_DEFINED,
                             /*  0xBA */ NOT_DEFINED,
                             /*  0xCA */ NOT_DEFINED,
                             /*  0xDA */ NOT_DEFINED,
                             /*  0xEA */ NOT_DEFINED,
                             /*  0xFA */ NOT_DEFINED,
/* FTrace_EVT_timer_post         0x0B */ NOT_DEFINED,
/* FTrace_EVT_timer_delete       0x1B */ NOT_DEFINED,
/* FTrace_EVT_timer_wakeup_start 0x2B */ NOT_DEFINED,
/* FTrace_EVT_timer_wakeup_end   0x3B */ NOT_DEFINED,
                             /*  0x4B */ NOT_DEFINED,
                             /*  0x5B */ NOT_DEFINED,
                             /*  0x6B */ NOT_DEFINED,
                             /*  0x7B */ NOT_DEFINED,
                             /*  0x8B */ NOT_DEFINED,
                             /*  0x9B */ NOT_DEFINED,
                             /*  0xAB */ NOT_DEFINED,
                             /*  0xBB */ NOT_DEFINED,
                             /*  0xCB */ NOT_DEFINED,
                             /*  0xDB */ NOT_DEFINED,
                             /*  0xEB */ NOT_DEFINED,
                             /*  0xFB */ NOT_DEFINED,
                             /*  0x0C */ NOT_DEFINED,
                             /*  0x1C */ NOT_DEFINED,
                             /*  0x2C */ NOT_DEFINED,
                             /*  0x3C */ NOT_DEFINED,
                             /*  0x4C */ NOT_DEFINED,
                             /*  0x5C */ NOT_DEFINED,
                             /*  0x6C */ NOT_DEFINED,
                             /*  0x7C */ NOT_DEFINED,
                             /*  0x8C */ NOT_DEFINED,
                             /*  0x9C */ NOT_DEFINED,
                             /*  0xAC */ NOT_DEFINED,
                             /*  0xBC */ NOT_DEFINED,
                             /*  0xCC */ NOT_DEFINED,
                             /*  0xDC */ NOT_DEFINED,
                             /*  0xEC */ NOT_DEFINED,
                             /*  0xFC */ NOT_DEFINED,
                             /*  0x0D */ NOT_DEFINED,
                             /*  0x1D */ NOT_DEFINED,
                             /*  0x2D */ NOT_DEFINED,
                             /*  0x3D */ NOT_DEFINED,
                             /*  0x4D */ NOT_DEFINED,
                             /*  0x5D */ NOT_DEFINED,
                             /*  0x6D */ NOT_DEFINED,
                             /*  0x7D */ NOT_DEFINED,
                             /*  0x8D */ NOT_DEFINED,
                             /*  0x9D */ NOT_DEFINED,
                             /*  0xAD */ NOT_DEFINED,
                             /*  0xBD */ NOT_DEFINED,
                             /*  0xCD */ NOT_DEFINED,
                             /*  0xDD */ NOT_DEFINED,
                             /*  0xED */ NOT_DEFINED,
                             /*  0xFD */ NOT_DEFINED,
                             /*  0x0E */ NOT_DEFINED,
                             /*  0x1E */ NOT_DEFINED,
                             /*  0x2E */ NOT_DEFINED,
                             /*  0x3E */ NOT_DEFINED,
                             /*  0x4E */ NOT_DEFINED,
                             /*  0x5E */ NOT_DEFINED,
                             /*  0x6E */ NOT_DEFINED,
                             /*  0x7E */ NOT_DEFINED,
                             /*  0x8E */ NOT_DEFINED,
                             /*  0x9E */ NOT_DEFINED,
                             /*  0xAE */ NOT_DEFINED,
                             /*  0xBE */ NOT_DEFINED,
                             /*  0xCE */ NOT_DEFINED,
                             /*  0xDE */ NOT_DEFINED,
                             /*  0xEE */ NOT_DEFINED,
                             /*  0xFE */ NOT_DEFINED,
                             /*  0x0F */ NOT_DEFINED,
                             /*  0x1F */ NOT_DEFINED,
                             /*  0x2F */ NOT_DEFINED,
                             /*  0x3F */ NOT_DEFINED,
                             /*  0x4F */ NOT_DEFINED,
                             /*  0x5F */ NOT_DEFINED,
                             /*  0x6F */ NOT_DEFINED,
                             /*  0x7F */ NOT_DEFINED,
                             /*  0x8F */ NOT_DEFINED,
                             /*  0x9F */ NOT_DEFINED,
                             /*  0xAF */ NOT_DEFINED,
                             /*  0xBF */ NOT_DEFINED,
                             /*  0xCF */ NOT_DEFINED,
                             /*  0xDF */ NOT_DEFINED,
                             /*  0xEF */ NOT_DEFINED,
                             /*  0xFF */ NOT_DEFINED};
