# The DIDMA library 

ifndef BASE
BASE=../..
endif

include $(BASE)/config/config.mk

LIBRARY = didma

OBJS_PATH = $(BASE)/ports/didma

# Object files
OTHERINCL=-I ./include
OBJS = didma.o

include $(BASE)/config/lib.mk

