# The PCL833 library

ifndef BASE
BASE=../..
endif

include $(BASE)/config/config.mk

LIBRARY       = pcl833

OBJS_PATH     = $(BASE)/drivers/pcl833

OBJS  = pcl833.o

OTHERINCL += -I./include

include $(BASE)/config/lib.mk

